### ISSUE TITLE
Pet-Calling does not work (Cow)

### ISSUE THREAD

**Issue by Jakllp** [Jakllp/MyPet#1]
# Bug report

Calling a pet does not work - wow that's a basic function

## To Reproduce

1. /pc

Probably doesn't work with any pet

**Error:**
```
[23:18:14 INFO]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] de.Keyle.MyPet.compat.v1_17_R1.entity.types.EntityMyCow(Cow) is no valid MyPet(Entity)!
[23:18:14 WARN]: java.lang.reflect.InvocationTargetException
[23:18:14 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23:18:14 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[23:18:14 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[23:18:14 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[23:18:14 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[23:18:14 WARN]:        at MyPet-3.12-SNAPSHOT.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityRegistry.createMinecraftEntity(EntityRegistry.java:92)
[23:18:14 WARN]:        at MyPet-3.12-SNAPSHOT.jar//de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:473)
[23:18:14 WARN]:        at MyPet-3.12-SNAPSHOT.jar//de.Keyle.MyPet.util.player.MyPetPlayerImpl.schedule(MyPetPlayerImpl.java:481)
[23:18:14 WARN]:        at MyPet-3.12-SNAPSHOT.jar//de.Keyle.MyPet.api.util.Timer.lambda$startTimer$2(Timer.java:62)
[23:18:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[23:18:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[23:18:14 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1490)
[23:18:14 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
[23:18:14 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406)
[23:18:14 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
[23:18:14 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[23:18:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[23:18:14 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeProvider.a(java.util.function.Consumer, net.minecraft.world.entity.ai.attributes.AttributeBase)" because "this.d" is null
[23:18:14 WARN]:        at net.minecraft.world.entity.ai.attributes.AttributeMapBase.lambda$getInstance$1(AttributeMapBase.java:50)
[23:18:14 WARN]:        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
[23:18:14 WARN]:        at net.minecraft.world.entity.ai.attributes.AttributeMapBase.a(AttributeMapBase.java:49)
[23:18:14 WARN]:        at net.minecraft.world.entity.EntityLiving.getAttributeInstance(EntityLiving.java:2407)
[23:18:14 WARN]:        at net.minecraft.world.entity.EntityLiving.<init>(EntityLiving.java:293)
[23:18:14 WARN]:        at net.minecraft.world.entity.EntityInsentient.<init>(EntityInsentient.java:131)
[23:18:14 WARN]:        at MyPet-3.12-SNAPSHOT.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.<init>(EntityMyPet.java:149)
[23:18:14 WARN]:        at MyPet-3.12-SNAPSHOT.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.types.EntityMyCow.<init>(EntityMyCow.java:44)
[23:18:14 WARN]:        ... 17 more
```

**Comment by Jakllp** [comment]
Best guess:
It wants a "Cow" value but would only get "n" as n is now a Cow - will check
