### ISSUE TITLE
Bug: Packet-Handling-Error - Asynchronous Chunk getEntities

### ISSUE THREAD

**Issue by Jakllp** [Jakllp/MyPet#12]
This error occurs fairly often and isn't really tied to a command.
I often saw it after interacting with the pet in some way.

```
[23:22:14] [Netty Epoll Server IO #1/ERROR]: [MyPet] Unhandled exception occured in onPacketReceiving(PacketEvent) for MyPet
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Paper-188]
	at net.minecraft.server.level.WorldServer.getEntities(WorldServer.java:2052) ~[patched_1.17.1.jar:git-Paper-188]
	at net.minecraft.server.level.WorldServer.getEntity(WorldServer.java:1483) ~[patched_1.17.1.jar:git-Paper-188]
	at de.Keyle.MyPet.compat.v1_17_R1.PlatformHelper.getEntity(PlatformHelper.java:352) ~[MyPet-3.12-SNAPSHOT.jar:?]
	at de.Keyle.MyPet.util.hooks.ProtocolLibHook$1.onPacketReceiving(ProtocolLibHook.java:108) ~[MyPet-3.12-SNAPSHOT.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:360) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:325) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-188]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [patched_1.17.1.jar:git-Paper-188]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:22:14] [Netty Epoll Server IO #1/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayInUseEntity@13b86da6[
    a=225
    b=net.minecraft.network.protocol.game.PacketPlayInUseEntity$1@682248bd
    c=false
  ]
```

**Comment by Jakllp** [comment]
Fixed in https://github.com/Jakllp/MyPet/commit/31a5945f5f473cea3bb333d29c69748d7b62e9bf

**Comment by Jakllp** [comment]
https://paste.ubuntu.com/p/MtpkTpFGP5/

Still a problem?

**Comment by Jakllp** [comment]
Check for relation to #29 and #23

**Comment by Jakllp** [comment]
No relations found. Seems to be a ProtocolLib-Issue?
Protocollib internal function calls getEntities. We'll see if I'm wrong (might be)
