### ISSUE TITLE
Bug: Pet riding not working (properly)

### ISSUE THREAD

**Issue by UmNyom** [Jakllp/MyPet#13]
The following error occurs when trying to ride a pet.
```
[09:30:33 WARN]: java.lang.UnsupportedOperationException
[09:30:33 WARN]:        at com.google.common.collect.ImmutableList.add(ImmutableList.java:523)
[09:30:33 WARN]:        at MyPet-3.12-dev3.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.addPassenger(EntityMyPet.java:1122)
[09:30:33 WARN]:        at net.minecraft.world.entity.Entity.a(Entity.java:2819)
[09:30:33 WARN]:        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1388)
[09:30:33 WARN]:        at net.minecraft.world.entity.Entity.startRiding(Entity.java:2793)
[09:30:33 WARN]:        at MyPet-3.12-dev3.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.handlePlayerInteraction(EntityMyPet.java:525)
[09:30:33 WARN]:        at MyPet-3.12-dev3.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.types.EntityMyOcelot.handlePlayerInteraction(EntityMyOcelot.java:64)
[09:30:33 WARN]:        at MyPet-3.12-dev3.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.b(EntityMyPet.java:965)
[09:30:33 WARN]:        at net.minecraft.world.entity.EntityInsentient.a(EntityInsentient.java:1250)
[09:30:33 WARN]:        at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:1084)
[09:30:33 WARN]:        at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2461)
[09:30:33 WARN]:        at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2480)
[09:30:33 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity$d.a(PacketPlayInUseEntity.java:131)
[09:30:33 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[09:30:33 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2422)
[09:30:33 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[09:30:33 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[09:30:33 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[09:30:33 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:152)
[09:30:33 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:24)
[09:30:33 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:124)
[09:30:33 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1423)
[09:30:33 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1416)
[09:30:33 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:135)
[09:30:33 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1389)
[09:30:33 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1299)
[09:30:33 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[09:30:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

But I think a lot of errors have been solved and I think it's getting better. I always thank the developer for trying to solve this problem.
>

**Comment by Jakllp** [comment]
Somewhat fixed in https://github.com/Jakllp/MyPet/commit/afad89b9b4a8bfd45f1929bd8c4c29c7226ea64e

Speed is still a problem. Made it a bit better

**Comment by Jakllp** [comment]
They are speedy now (https://github.com/Jakllp/MyPet/commit/70a7289e770afece3ef7cb6733bf7e5790720545) but they still can't jump

**Comment by Jakllp** [comment]
Properly fixed in https://github.com/Jakllp/MyPet/commit/dab7fcfda766563506daac8373038e457827766e

Release: https://github.com/Jakllp/MyPet/releases/tag/v1.17.1-dev6
