### ISSUE TITLE
Bug: Skilltree Error Combat and PvP

### ISSUE THREAD

**Issue by Sponge1996** [Jakllp/MyPet#16]
MyPet v3.12 dev3 newest Version

**Error:**
```
[18:00:15 WARN]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Task #2 for MyPet v3.12 generated an exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.network.syncher.DataWatcher$Item.b()" because "datawatcher_item" is null
        at net.minecraft.network.syncher.DataWatcher.set(DataWatcher.java:141) ~[patched_1.17.1.jar:git-Paper-196]
        at de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.showPotionParticles(EntityMyPet.java:404) ~[MyPet-3.12-dev3.jar:?]
        at de.Keyle.MyPet.skill.skills.HealImpl.lambda$schedule$0(HealImpl.java:79) ~[MyPet-3.12-dev3.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at de.Keyle.MyPet.skill.skills.HealImpl.schedule(HealImpl.java:73) ~[MyPet-3.12-dev3.jar:?]
        at de.Keyle.MyPet.entity.MyPet.schedule(MyPet.java:651) ~[MyPet-3.12-dev3.jar:?]
        at de.Keyle.MyPet.entity.types.MySheep.schedule(MySheep.java:51) ~[MyPet-3.12-dev3.jar:?]
        at de.Keyle.MyPet.api.util.Timer.lambda$startTimer$0(Timer.java:52) ~[MyPet-3.12-dev3.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Jakllp** [comment]
Potentially fixed in https://github.com/Jakllp/MyPet/commit/56517a03572391493e45ae4c1d4c0d5e98b98786

**Comment by Jakllp** [comment]
Fixed.
