### ISSUE TITLE
1.17.1 errors

### ISSUE THREAD

**Issue by andris155** [Jakllp/MyPet#2]
ToDo (meaning the console-errors):

- [x] /petshop
- [x] /petswitch
- [x] /petstore
- [ ] Packet-Error (here under /pch)
- [x] Actually spawning animals

The /pc command not work if you have a pet:
<img width="340" alt="Screenshot 2021-08-17 232119" src="https://user-images.githubusercontent.com/8324198/129802877-18797c3b-e4fa-44e1-b4a9-069d43c9525a.png">
```
[23:18:14 INFO]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] de.Keyle.MyPet.compat.v1_17_R1.entity.types.EntityMyCow(Cow) is no valid MyPet(Entity)!
[23:18:14 WARN]: java.lang.reflect.InvocationTargetException
[23:18:14 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23:18:14 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[23:18:14 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[23:18:14 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[23:18:14 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[23:18:14 WARN]:        at MyPet-3.12-SNAPSHOT.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityRegistry.createMinecraftEntity(EntityRegistry.java:92)
[23:18:14 WARN]:        at MyPet-3.12-SNAPSHOT.jar//de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:473)
[23:18:14 WARN]:        at MyPet-3.12-SNAPSHOT.jar//de.Keyle.MyPet.util.player.MyPetPlayerImpl.schedule(MyPetPlayerImpl.java:481)
[23:18:14 WARN]:        at MyPet-3.12-SNAPSHOT.jar//de.Keyle.MyPet.api.util.Timer.lambda$startTimer$2(Timer.java:62)
[23:18:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[23:18:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[23:18:14 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1490)
[23:18:14 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
[23:18:14 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406)
[23:18:14 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
[23:18:14 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[23:18:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[23:18:14 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeProvider.a(java.util.function.Consumer, net.minecraft.world.entity.ai.attributes.AttributeBase)" because "this.d" is null
[23:18:14 WARN]:        at net.minecraft.world.entity.ai.attributes.AttributeMapBase.lambda$getInstance$1(AttributeMapBase.java:50)
[23:18:14 WARN]:        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
[23:18:14 WARN]:        at net.minecraft.world.entity.ai.attributes.AttributeMapBase.a(AttributeMapBase.java:49)
[23:18:14 WARN]:        at net.minecraft.world.entity.EntityLiving.getAttributeInstance(EntityLiving.java:2407)
[23:18:14 WARN]:        at net.minecraft.world.entity.EntityLiving.<init>(EntityLiving.java:293)
[23:18:14 WARN]:        at net.minecraft.world.entity.EntityInsentient.<init>(EntityInsentient.java:131)
[23:18:14 WARN]:        at MyPet-3.12-SNAPSHOT.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.<init>(EntityMyPet.java:149)
[23:18:14 WARN]:        at MyPet-3.12-SNAPSHOT.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.types.EntityMyCow.<init>(EntityMyCow.java:44)
[23:18:14 WARN]:        ... 17 more
```

The /pch command causes errors if have near entities:
```
[23:22:14] [Netty Epoll Server IO #1/ERROR]: [MyPet] Unhandled exception occured in onPacketReceiving(PacketEvent) for MyPet
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Paper-188]
	at net.minecraft.server.level.WorldServer.getEntities(WorldServer.java:2052) ~[patched_1.17.1.jar:git-Paper-188]
	at net.minecraft.server.level.WorldServer.getEntity(WorldServer.java:1483) ~[patched_1.17.1.jar:git-Paper-188]
	at de.Keyle.MyPet.compat.v1_17_R1.PlatformHelper.getEntity(PlatformHelper.java:352) ~[MyPet-3.12-SNAPSHOT.jar:?]
	at de.Keyle.MyPet.util.hooks.ProtocolLibHook$1.onPacketReceiving(ProtocolLibHook.java:108) ~[MyPet-3.12-SNAPSHOT.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:360) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:325) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-188]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289) [ProtocolLib.jar:4.7.1-SNAPSHOT-b531]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [patched_1.17.1.jar:git-Paper-188]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [patched_1.17.1.jar:git-Paper-188]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:22:14] [Netty Epoll Server IO #1/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayInUseEntity@13b86da6[
    a=225
    b=net.minecraft.network.protocol.game.PacketPlayInUseEntity$1@682248bd
    c=false
  ]
```

The /petshop command causes errors:
<img width="463" alt="Screenshot 2021-08-17 233057" src="https://user-images.githubusercontent.com/8324198/129803357-54683465-04e1-4535-b858-6b8f80b2d7c6.png">

```
[23:28:24 WARN]: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem
[23:28:24 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[23:28:24 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[23:28:24 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[23:28:24 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[23:28:24 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[23:28:24 WARN]:        at MyPet-3.12-SNAPSHOT.jar//de.Keyle.MyPet.compat.v1_17_R1.util.iconmenu.IconMenuInventory.<clinit>(IconMenuInventory.java:58)
[23:28:24 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[23:28:24 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[23:28:24 WARN]:        at MyPet-3.12-SNAPSHOT.jar//de.Keyle.MyPet.api.util.CompatUtil.getComapatInstance(CompatUtil.java:67)
[23:28:24 WARN]:        at MyPet-3.12-SNAPSHOT.jar//de.Keyle.MyPet.api.gui.IconMenu.open(IconMenu.java:95)
[23:28:24 WARN]:        at MyPet-3.12-SNAPSHOT.jar//de.Keyle.MyPet.commands.CommandShop.onCommand(CommandShop.java:149)
[23:28:24 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[23:28:24 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[23:28:24 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:832)
[23:28:24 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2169)
[23:28:24 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1980)
[23:28:24 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1961)
[23:28:24 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[23:28:24 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[23:28:24 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[23:28:24 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[23:28:24 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[23:28:24 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[23:28:24 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[23:28:24 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[23:28:24 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[23:28:24 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[23:28:24 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[23:28:24 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[23:28:24 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281)
[23:28:24 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192)
[23:28:24 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[23:28:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[23:28:24 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'petshop' in plugin MyPet v3.12
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Paper-188]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-188]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:832) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2169) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1980) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1961) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-188]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.server.level.EntityPlayer cannot be cast to class net.minecraft.world.inventory.ICrafting (net.minecraft.server.level.EntityPlayer and net.minecraft.world.inventory.ICrafting are in unnamed module of loader 'app')
        at de.Keyle.MyPet.compat.v1_17_R1.util.inventory.CustomInventory.open(CustomInventory.java:329) ~[MyPet-3.12-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.compat.v1_17_R1.util.iconmenu.IconMenuInventory.open(IconMenuInventory.java:84) ~[MyPet-3.12-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.api.gui.IconMenu.open(IconMenu.java:97) ~[MyPet-3.12-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.commands.CommandShop.onCommand(CommandShop.java:149) ~[MyPet-3.12-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-188]
        ... 21 more
```

The /petswitch command causes errors:
```
[23:31:16 WARN]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Task #7111 for MyPet v3.12 generated an exception
java.lang.ClassCastException: class net.minecraft.server.level.EntityPlayer cannot be cast to class net.minecraft.world.inventory.ICrafting (net.minecraft.server.level.EntityPlayer and net.minecraft.world.inventory.ICrafting are in unnamed module of loader 'app')
        at de.Keyle.MyPet.compat.v1_17_R1.util.inventory.CustomInventory.open(CustomInventory.java:329) ~[MyPet-3.12-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.compat.v1_17_R1.util.iconmenu.IconMenuInventory.open(IconMenuInventory.java:84) ~[MyPet-3.12-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.api.gui.IconMenu.open(IconMenu.java:97) ~[MyPet-3.12-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.gui.selectionmenu.MyPetSelectionGui.open(MyPetSelectionGui.java:172) ~[MyPet-3.12-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.gui.selectionmenu.MyPetSelectionGui.open(MyPetSelectionGui.java:68) ~[MyPet-3.12-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.commands.CommandSwitch$1.callback(CommandSwitch.java:94) ~[MyPet-3.12-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.commands.CommandSwitch$1.callback(CommandSwitch.java:71) ~[MyPet-3.12-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.api.repository.RepositoryCallback.run(RepositoryCallback.java:37) ~[MyPet-3.12-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-188]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-188]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-188]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

The /petstore command causes errors:
```
[23:32:10 WARN]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Plugin MyPet v3.12 generated an exception while executing task 7226
java.lang.IllegalArgumentException: No enum constant de.Keyle.MyPet.api.util.service.types.RepositoryMyPetConverterService.Version.v1_17_R1
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at de.Keyle.MyPet.api.util.service.types.RepositoryMyPetConverterService$Version.valueOf(RepositoryMyPetConverterService.java:38) ~[MyPet-3.12-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.entity.MyPet.writeExtendedInfo(MyPet.java:193) ~[MyPet-3.12-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.entity.types.MyPig.writeExtendedInfo(MyPig.java:43) ~[MyPet-3.12-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.entity.MyPet.getInfo(MyPet.java:93) ~[MyPet-3.12-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.repository.types.SqLiteRepository$9.run(SqLiteRepository.java:699) ~[MyPet-3.12-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-188]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [patched_1.17.1.jar:git-Paper-188]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.17.1.jar:git-Paper-188]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Jakllp** [comment]
I MIGHT have an idea what could cause the first error and potentially even more... Is there a way I can send you another jar that has a minimal test-fix? Or do you want to do it yourself (it's literally 1 line) and then compile it yourself?

**Comment by Jakllp** [comment]
The error you connected to /pch is actually an error that occurs quite a lot. It's not specific to /pch but seems quite... Well... Problematic to fix at first glance

**Comment by Jakllp** [comment]
ToDo (meaning the console-errors):

- [ ] /petshop
- [ ] /petswitch
- [ ] /petstore
- [ ] Packet-Error
- [ ] Actually spawning animals

**Comment by Jakllp** [comment]
Got /petshop and /petswitch to work locally
Also fixed the /petstore error locally as I stumbled across the cause looking for reasons the spawning is failing

Well... The icons are missing but yeah. No errors in console.
Spawning is another beast and the packet error... Well

**Comment by Jakllp** [comment]
https://github.com/Jakllp/MyPet/commit/e5ba2b73e130510615dbf5e08f177d2406e9f9c3
Addresses:
/petshop
/petswitch
/petstore

Also: Cows should now spawn as pigs... Yeah... Left it in for others to see if they can make sense of it

**Comment by Jakllp** [comment]
https://github.com/Jakllp/MyPet/commit/b279ce505839e44f65c8f8c87bdbda0316f5d241
Fixed pet-spawning

jar: https://github.com/Jakllp/MyPet/releases/tag/v1.17.1-dev2

**Comment by Jakllp** [comment]
Will open separate issue for the Packet-Error just for organization's sake

Therefore this one is closed
