### ISSUE TITLE
Failed to call entity

### ISSUE THREAD

**Issue by jsramirezch** [Jakllp/MyPet#27]
```
[MyPet] Version 3.10-b1542 ENABLED
08-24-2021 01:51 [WARNING] [MyPet] Task #211 for MyPet v3.1 generated an exception
java.lang.AbstractMethodError: Method de/Keyle/MyPet/compat/v1_12_R1/entity/types/EntityMyEnderman.getUniqueID()Ljava/util/UUID; is abstract
	at de.Keyle.MyPet.compat.v1_12_R1.entity.types.EntityMyEnderman.getUniqueID(EntityMyEnderman.java)
	at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:501)
	at java.util.Optional.ifPresent(Unknown Source)
	at de.Keyle.MyPet.listeners.EntityListener$2.callback(EntityListener.java:382)
	at de.Keyle.MyPet.listeners.EntityListener$2.callback(EntityListener.java:376)
	at de.Keyle.MyPet.api.repository.RepositoryCallback.run(RepositoryCallback.java:37)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:65)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:429)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:917)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737)
	at java.lang.Thread.run(Unknown Source)
08-24-2021 01:51 [WARNING] [MyPet] Task #15 for MyPet v3.1 generated an exception
java.lang.AbstractMethodError: Method de/Keyle/MyPet/compat/v1_12_R1/entity/types/EntityMyEnderman.getUniqueID()Ljava/util/UUID; is abstract
	at de.Keyle.MyPet.compat.v1_12_R1.entity.types.EntityMyEnderman.getUniqueID(EntityMyEnderman.java)
	at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:501)
	at de.Keyle.MyPet.util.player.MyPetPlayerImpl.schedule(MyPetPlayerImpl.java:481)
	at de.Keyle.MyPet.api.util.Timer.lambda$startTimer$2(Timer.java:62)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:65)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:429)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:917)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737)
	at java.lang.Thread.run(Unknown Source)
```
![image](https://user-images.githubusercontent.com/83787987/130573209-86cbf865-6883-44c3-be3b-ce988945c52b.png)

**Comment by Jakllp** [comment]
Am I seeing it correctly that you are running version 3.10?

**Comment by CJBlakey** [comment]
> Am I seeing it correctly that you are running MyPet version 3.10 on Minecraft 1.12?

Certainly looks like that

**Comment by Jakllp** [comment]
@jsramirezch
Please try the same thing with the Dev version (3.11-SNAPSHOT) found here: https://mypet-plugin.de/download and report back

**Comment by jsramirezch** [comment]
![image](https://user-images.githubusercontent.com/83787987/130702781-db8fdfc5-b1a3-48b7-91db-635ab8ebbb0a.png)
![image](https://user-images.githubusercontent.com/83787987/130702909-a0ba5bdd-728e-4cb3-a871-a82b28317952.png)
I've already tried


[18:28:27] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: DarkShakez issued server command: /petc
[18:28:27] [Server thread/ERROR] [net.minecraft.network.NetHandlerPlayServer]: null
 org.bukkit.command.CommandException: Unhandled exception executing command 'petc' in plugin MyPet v3.11
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[PluginCommand.class:761933c-STABLE]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:153) ~[SimpleCommandMap.class:761933c-STABLE]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:689) ~[CraftServer.class:761933c-STABLE]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1604) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1452) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:50) ~[la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:11) ~[la.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:14) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_301]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_301]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:926) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.AbstractMethodError: Method de/Keyle/MyPet/compat/v1_12_R1/entity/types/EntityMyEnderman.getUniqueID()Ljava/util/UUID; is abstract
        at de.Keyle.MyPet.compat.v1_12_R1.entity.types.EntityMyEnderman.getUniqueID(EntityMyEnderman.java) ~[MyPet-3.10.jar:?]
        at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:501) ~[MyPet-3.10.jar:?]
        at de.Keyle.MyPet.commands.CommandCall.onCommand(CommandCall.java:50) ~[MyPet-3.10.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:761933c-STABLE]
        ... 15 more

**Comment by Jakllp** [comment]
Only happens with enderman?

**Comment by jsramirezch** [comment]
![image](https://user-images.githubusercontent.com/83787987/130704336-27463f13-a8af-427b-a285-34552d2172ea.png)
![image](https://user-images.githubusercontent.com/83787987/130704458-02bfb958-aae2-4b37-9558-f32acaa32639.png)

The server uses magma
And i have these plugins
![image](https://user-images.githubusercontent.com/83787987/130704648-e3b2030d-e59e-4a57-8a6a-1a6a99b408ba.png)

**Comment by jsramirezch** [comment]
Could it be a conflict with another plugin?

**Comment by Jakllp** [comment]
I don't really know. To be honest I don't even really know the 1.12 code for this plugin as this is the 1.17.1 branch (but I wanted to help anyway) - It calls the UUID but MyPet isn't returning it as it didnt overwrite it... Mhh

**Comment by jsramirezch** [comment]
As additional information the server has mods, however all the commands work correctly except / pc or / petc

**Comment by jsramirezch** [comment]
I will be looking for solutions, if I find any I will not hesitate to provide it

**Comment by Jakllp** [comment]
I think I know what's up

**Comment by jsramirezch** [comment]
Wonderful, I will be looking forward to this version, since I have a project in mind with this beautiful plugin, I really appreciate your attention, support and effort that you put into this project.

**Comment by jsramirezch** [comment]
I have since version 1.7.2 using their my pet plugin on all my servers.

**Comment by Jakllp** [comment]
https://github.com/Jakllp/MyPet/releases/tag/v1.17.1-dev5.1

Try this. It might not work at all, it should tho. And it should fix the problem

**Comment by jsramirezch** [comment]
[20:10:41] [Server thread/WARN] [de.Keyle.MyPet.MyPetPlugin]: [MyPet] Task #63 for MyPet v3.12 generated an exception
 java.lang.AbstractMethodError: Method de/Keyle/MyPet/compat/v1_12_R1/entity/types/EntityMySheep.getUniqueID()Ljava/util/UUID; is abstract
        at de.Keyle.MyPet.compat.v1_12_R1.entity.types.EntityMySheep.getUniqueID(EntityMySheep.java) ~[MyPet-3.12-dev5.1.jar:?]
        at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:501) ~[MyPet-3.12-dev5.1.jar:?]
        at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_301]
        at de.Keyle.MyPet.listeners.EntityListener$2.callback(EntityListener.java:382) ~[MyPet-3.12-dev5.1.jar:?]
        at de.Keyle.MyPet.listeners.EntityListener$2.callback(EntityListener.java:376) ~[MyPet-3.12-dev5.1.jar:?]
        at de.Keyle.MyPet.api.repository.RepositoryCallback.run(RepositoryCallback.java:37) ~[MyPet-3.12-dev5.1.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:65) ~[CraftTask.class:761933c-STABLE]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:429) [CraftScheduler.class:761933c-STABLE]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:917) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
[20:10:41] [Server thread/ERROR] [global]: TIMING_STACK_CORRUPTION - Report this to the plugin MyPet(Look for errors above this in the logs) (TimingIdentifier{id=MyPet:Task: null (Single)} did not stopTiming)
 java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:113) [TimingHandler.class:761933c-STABLE]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:918) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
>
![image](https://user-images.githubusercontent.com/83787987/130710198-f6d12b45-6046-4c8d-9407-832150162542.png)

**Comment by jsramirezch** [comment]
![image](https://user-images.githubusercontent.com/83787987/130713482-e0e76e69-905b-4822-afb7-0e5b0af4d53c.png)
Problem resulted

**Comment by jsramirezch** [comment]
Magma had compatibility problems, I switched to mohist-1.12.2-248-server and the plugin worked correctly

**Comment by jsramirezch** [comment]
Thank you very much Jakllp for the support.
