### ISSUE TITLE
Bug: Slime doesn't spawn

### ISSUE THREAD

**Issue by M1904** [Jakllp/MyPet#40]
Paperspigot 1.17.1

MyPet-1.17.1-dev7 

error when click in the /petswitch-GUI on the slime-spawn-egg

```
[23:23:04] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [m[0;31;1mde.Keyle.MyPet.compat.v1_17_R1.entity.types.EntityMySlime(Slime) is no valid MyPet(Entity)![m
[23:23:04] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[23:23:04] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedConstructorAccessor126.newInstance(Unknown Source)
[23:23:04] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[23:23:04] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[23:23:04] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[23:23:04] [Server thread/WARN]: 	at de.Keyle.MyPet.compat.v1_17_R1.entity.EntityRegistry.createMinecraftEntity(EntityRegistry.java:90)
[23:23:04] [Server thread/WARN]: 	at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:473)
[23:23:04] [Server thread/WARN]: 	at de.Keyle.MyPet.commands.CommandSwitch$1$1.callback(CommandSwitch.java:104)
[23:23:04] [Server thread/WARN]: 	at de.Keyle.MyPet.commands.CommandSwitch$1$1.callback(CommandSwitch.java:94)
[23:23:04] [Server thread/WARN]: 	at de.Keyle.MyPet.gui.selectionmenu.MyPetSelectionGui.lambda$open$0(MyPetSelectionGui.java:116)
[23:23:04] [Server thread/WARN]: 	at de.Keyle.MyPet.api.gui.IconMenu.on(IconMenu.java:146)
[23:23:04] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[23:23:04] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[23:23:04] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[23:23:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2715)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:55)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:11)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[23:23:04] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[23:23:04] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: Can't find attribute minecraft:generic.follow_range
[23:23:04] [Server thread/WARN]: 	at net.minecraft.world.entity.ai.attributes.AttributeProvider.d(AttributeProvider.java:22)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.world.entity.ai.attributes.AttributeProvider.a(AttributeProvider.java:28)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.world.entity.ai.attributes.AttributeMapBase.c(AttributeMapBase.java:65)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityLiving.b(EntityLiving.java:2410)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.world.entity.ai.navigation.NavigationAbstract.<init>(NavigationAbstract.java:55)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.world.entity.ai.navigation.Navigation.<init>(Navigation.java:22)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityInsentient.a(EntityInsentient.java:169)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityInsentient.<init>(EntityInsentient.java:145)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityCreature.<init>(EntityCreature.java:19)
[23:23:04] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityAgeable.<init>(EntityAgeable.java:25)
[23:23:04] [Server thread/WARN]: 	at de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.<init>(EntityMyPet.java:164)
[23:23:04] [Server thread/WARN]: 	at de.Keyle.MyPet.compat.v1_17_R1.entity.types.EntityMySlime.<init>(EntityMySlime.java:42)
[23:23:04] [Server thread/WARN]: 	... 31 more
```

**Comment by Jakllp** [comment]
Might also be the case for other mobs - depending on what solves this

**Comment by Jakllp** [comment]
Fixed in https://github.com/Jakllp/MyPet/commit/19c4b15203f171a98a6c6da99fd36deae6ee8625
