### ISSUE TITLE
Bug: petinventory and NBTItems error

### ISSUE THREAD

**Issue by M1904** [Jakllp/MyPet#43]
Hello, me again :P

you do a great work to update this plugin. I loaded the plugin in eclipse and closed it again immediately because of the tons of packages and classes. ^^

Server: Paperspigot 1.17.1
            MyPet 3.12 dev7

enchanted Items or other items with NBT-data cannot be stored in petinventory

[20:09:54] [Craft Scheduler Thread - 1526/WARN]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [m[0;31;1mPlugin MyPet v3.12 generated an exception while executing task 7410386[m
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "de.Keyle.MyPet.compat.v1_17_R1.util.inventory.ItemStackNBTConverter.TAG_LIST_LIST" is null
	at de.Keyle.MyPet.compat.v1_17_R1.util.inventory.ItemStackNBTConverter.vanillaCompoundToCompound(ItemStackNBTConverter.java:118) ~[?:?]
	at de.Keyle.MyPet.compat.v1_17_R1.util.inventory.ItemStackNBTConverter.vanillaCompoundToCompound(ItemStackNBTConverter.java:132) ~[?:?]
	at de.Keyle.MyPet.compat.v1_17_R1.util.inventory.ItemStackNBTConverter.vanillaCompoundToCompound(ItemStackNBTConverter.java:132) ~[?:?]
	at de.Keyle.MyPet.compat.v1_17_R1.util.inventory.ItemStackNBTConverter.itemStackToCompound(ItemStackNBTConverter.java:48) ~[?:?]
	at de.Keyle.MyPet.compat.v1_17_R1.util.inventory.CustomInventory.save(CustomInventory.java:238) ~[?:?]
	at de.Keyle.MyPet.skill.skills.BackpackImpl.save(BackpackImpl.java:115) ~[?:?]
	at de.Keyle.MyPet.entity.MyPet.getSkillInfo(MyPet.java:338) ~[?:?]
	at de.Keyle.MyPet.repository.types.MySqlRepository$9.run(MySqlRepository.java:786) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-140]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-140]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-140]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Jakllp** [comment]
Fixed in https://github.com/Jakllp/MyPet/commit/19c4b15203f171a98a6c6da99fd36deae6ee8625 (couldn't have known that it was the same issue)

Release will follow soon, thank you for the kind works and the testing ^^
