### ISSUE TITLE
Bug: Villager-Catching results in Cast-Exception

### ISSUE THREAD

**Issue by Jakllp** [Jakllp/MyPet#44]
When hitting a Villager to get it as a pet the following error occurs

```
[22:48:44 ERROR]: Could not pass event EntityDamageByEntityEvent to MyPet v3.12
java.lang.ClassCastException: class net.minecraft.nbt.NBTTagIntArray cannot be cast to class de.Keyle.MyPet.util.nbt.TagIntArray (net.minecraft.nbt.NBTTagIntArray is in unnamed module of loader 'app'; de.Keyle.MyPet.util.nbt.TagIntArray is in unnamed module of loader 'MyPet-3.12-dev7.jar' @42448126)
	at de.Keyle.MyPet.compat.v1_17_R1.util.inventory.ItemStackNBTConverter.vanillaCompoundToCompound(ItemStackNBTConverter.java:136) ~[MyPet-3.12-dev7.jar:?]
	at de.Keyle.MyPet.compat.v1_17_R1.util.inventory.ItemStackNBTConverter.vanillaCompoundToCompound(ItemStackNBTConverter.java:132) ~[MyPet-3.12-dev7.jar:?]
	at de.Keyle.MyPet.compat.v1_17_R1.util.inventory.ItemStackNBTConverter.vanillaCompoundToCompound(ItemStackNBTConverter.java:120) ~[MyPet-3.12-dev7.jar:?]
	at de.Keyle.MyPet.compat.v1_17_R1.util.inventory.ItemStackNBTConverter.vanillaCompoundToCompound(ItemStackNBTConverter.java:132) ~[MyPet-3.12-dev7.jar:?]
	at de.Keyle.MyPet.compat.v1_17_R1.util.inventory.ItemStackNBTConverter.vanillaCompoundToCompound(ItemStackNBTConverter.java:120) ~[MyPet-3.12-dev7.jar:?]
	at de.Keyle.MyPet.compat.v1_17_R1.util.inventory.ItemStackNBTConverter.vanillaCompoundToCompound(ItemStackNBTConverter.java:132) ~[MyPet-3.12-dev7.jar:?]
	at de.Keyle.MyPet.compat.v1_17_R1.PlatformHelper.entityToTag(PlatformHelper.java:259) ~[MyPet-3.12-dev7.jar:?]
	at de.Keyle.MyPet.compat.v1_17_R1.services.EntityConverterService.convertVillager(EntityConverterService.java:546) ~[MyPet-3.12-dev7.jar:?]
	at de.Keyle.MyPet.compat.v1_17_R1.services.EntityConverterService.convertEntity(EntityConverterService.java:133) ~[MyPet-3.12-dev7.jar:?]
	at de.Keyle.MyPet.listeners.EntityListener.lambda$on$0(EntityListener.java:343) ~[MyPet-3.12-dev7.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at de.Keyle.MyPet.listeners.EntityListener.on(EntityListener.java:343) ~[MyPet-3.12-dev7.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor254.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-209]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-209]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-209]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-209]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:242) ~[patched_1.17.1.jar:git-Paper-209]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1103) ~[patched_1.17.1.jar:git-Paper-209]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:987) ~[patched_1.17.1.jar:git-Paper-209]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:943) ~[patched_1.17.1.jar:git-Paper-209]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1135) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.world.entity.EntityLiving.damageEntity0(EntityLiving.java:2042) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.world.entity.EntityLiving.damageEntity(EntityLiving.java:1350) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.world.entity.player.EntityHuman.attack(EntityHuman.java:1256) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.server.level.EntityPlayer.attack(EntityPlayer.java:1985) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2399) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(PacketPlayInUseEntity.java:24) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2326) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192) ~[patched_1.17.1.jar:git-Paper-209]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-209]
	at java.lang.Thread.run(Thread.java:831) [?:?]

```

**Comment by Jakllp** [comment]
Done in https://github.com/Jakllp/MyPet/commit/e7d2e38c8c214e6a892a0be4e9bd319efd6b678a
