### ISSUE TITLE
Add griefdefender-support

### ISSUE THREAD

**Issue by Jakllp** [Jakllp/MyPet#47]
griefdefender seems to be similar to griefprevention (according to @cobrex1)
Might be able to add support for it

**Comment by Sponge1996** [comment]
![image](https://user-images.githubusercontent.com/18584669/131447305-671538f5-07bb-493a-9afe-0746f01594cd.png)

**Comment by Jakllp** [comment]
![image](https://user-images.githubusercontent.com/57708725/131489454-e5f53864-fe2f-4963-8c92-3df259f09d71.png)

```
[14:07:46 WARN]: java.lang.UnsupportedOperationException
[14:07:46 WARN]:        at java.base/java.util.AbstractCollection.add(AbstractCollection.java:251)
[14:07:46 WARN]:        at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:336)
[14:07:46 WARN]:        at com.griefdefender.provider.LuckPermsProvider.addActiveContexts(LuckPermsProvider.java:467)
[14:07:46 WARN]:        at com.griefdefender.util.PermissionUtil.addActiveContexts(PermissionUtil.java:101)
[14:07:46 WARN]:        at com.griefdefender.permission.GDPermissionManager.getInternalOptionValue(GDPermissionManager.java:1675)
[14:07:46 WARN]:        at com.griefdefender.permission.GDPermissionManager.getActiveOptionValue(GDPermissionManager.java:2006)
[14:07:46 WARN]:        at griefdefender.jar//com.griefdefender.api.permission.PermissionManager.getActiveOptionValue(PermissionManager.java:327)
[14:07:46 WARN]:        at com.griefdefender.hooks.provider.MyPetProvider$GDMyPetFlyHook.canHurtEntity(MyPetProvider.java:134)
[14:07:46 WARN]:        at com.griefdefender.hooks.provider.MyPetProvider$GDMyPetFlyHook.canHurt(MyPetProvider.java:117)
[14:07:46 WARN]:        at MyPet.jar//de.Keyle.MyPet.util.HookHelper.canHurt(HookHelper.java:85)
[14:07:46 WARN]:        at MyPet.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.ai.target.OwnerHurtByTarget.shouldStart(OwnerHurtByTarget.java:97)
[14:07:46 WARN]:        at MyPet.jar//de.Keyle.MyPet.api.entity.ai.AIGoalSelector.tick(AIGoalSelector.java:120)
[14:07:46 WARN]:        at MyPet.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.doMyPetTick(EntityMyPet.java:1187)
[14:07:46 WARN]:        at MyPet.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.movementTick(EntityMyPet.java:1071)
[14:07:46 WARN]:        at net.minecraft.world.entity.EntityLiving.tick(EntityLiving.java:2881)
[14:07:46 WARN]:        at net.minecraft.world.entity.EntityInsentient.tick(EntityInsentient.java:393)
[14:07:46 WARN]:        at MyPet.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.tick(EntityMyPet.java:1387)
[14:07:46 WARN]:        at net.minecraft.server.level.WorldServer.entityJoinedWorld(WorldServer.java:903)
[14:07:46 WARN]:        at net.minecraft.world.level.World.a(World.java:869)
[14:07:46 WARN]:        at net.minecraft.server.level.WorldServer.lambda$tick$5(WorldServer.java:600)
[14:07:46 WARN]:        at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:54)
[14:07:46 WARN]:        at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:581)
[14:07:46 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1568)
[14:07:46 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
[14:07:46 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1421)
[14:07:46 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1203)
[14:07:46 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[14:07:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```
