### ISSUE TITLE
Bug: Goats throw an error on right click (missing grow_up_item)

### ISSUE THREAD

**Issue by Jakllp** [Jakllp/MyPet#51]
```
[14:38:12 WARN]: java.lang.NullPointerException: Cannot invoke "de.Keyle.MyPet.api.util.ConfigItem.compare(Object)" because "de.Keyle.MyPet.api.Configuration$MyPet$Goat.GROW_UP_ITEM" is null
[14:38:12 WARN]: 	at MyPet-3.12-RC1.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.types.EntityMyGoat.handlePlayerInteraction(EntityMyGoat.java:83)
[14:38:12 WARN]: 	at MyPet-3.12-RC1.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.b(EntityMyPet.java:965)
[14:38:12 WARN]: 	at net.minecraft.world.entity.EntityInsentient.a(EntityInsentient.java:1237)
[14:38:12 WARN]: 	at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:1084)
[14:38:12 WARN]: 	at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2444)
[14:38:12 WARN]: 	at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2463)
[14:38:12 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity$d.a(PacketPlayInUseEntity.java:131)
[14:38:12 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[14:38:12 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2405)
[14:38:12 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[14:38:12 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[14:38:12 WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[14:38:12 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:38:12 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[14:38:12 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[14:38:12 WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418)
[14:38:12 WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[14:38:12 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[14:38:12 WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396)
[14:38:12 WARN]: 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389)
[14:38:12 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[14:38:12 WARN]: 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1367)
[14:38:12 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1278)
[14:38:12 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[14:38:12 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
```

(should be fairly easy to fix - will do that myself)

**Comment by Jakllp** [comment]
Done in https://github.com/Jakllp/MyPet/commit/474496fd8ba5bf12738f0626552002dd7252acfb
