### ISSUE TITLE
Bug: Cannot release Villager?

### ISSUE THREAD

**Issue by Jakllp** [Jakllp/MyPet#53]
![image](https://user-images.githubusercontent.com/57708725/132061630-dadc05bd-1c99-4c39-9a5c-b5af66396eca.png)

**Comment by comonier** [comment]
no errors on my test on game or console
[08:17:16] [Server thread/INFO]: comonier issued server command: /pcst
[08:17:23] [Server thread/INFO]: comonier issued server command: /psw
[08:17:36] [Server thread/INFO]: comonier issued server command: /petrelease
[08:17:39] [Server thread/INFO]: comonier issued server command: /petrelease Vaca
[08:18:04] [Server thread/INFO]: comonier issued server command: /petadmin give comonier
[08:18:18] [Server thread/INFO]: comonier issued server command: /petadmin create comonier Villager
[08:18:22] [Server thread/INFO]: comonier issued server command: /petrelease
[08:18:24] [Server thread/INFO]: comonier issued server command: /petrelease Aldeão
[08:19:02] [Server thread/INFO]: comonier issued server command: /mypet

[08:23:51 INFO]: Checking version, please wait...
[08:23:51 INFO]: This server is running Paper version git-Paper-135 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 321dd1d)
You are 114 version(s) behind

**Comment by Ghost-chu** [comment]
```
[21:07:10 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'petrelease' in plugin MyPet v3.12
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Airplane-73]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Airplane-73]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838) ~[patched_1.17.1.jar:git-Airplane-73]
        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2248) ~[patched_1.17.1.jar:git-Airplane-73]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2059) ~[patched_1.17.1.jar:git-Airplane-73]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2040) ~[patched_1.17.1.jar:git-Airplane-73]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[patched_1.17.1.jar:git-Airplane-73]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6) ~[patched_1.17.1.jar:git-Airplane-73]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Airplane-73]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Airplane-73]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Airplane-73]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Airplane-73]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1421) ~[patched_1.17.1.jar:git-Airplane-73]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Airplane-73]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Airplane-73]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1399) ~[patched_1.17.1.jar:git-Airplane-73]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1392) ~[patched_1.17.1.jar:git-Airplane-73]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Airplane-73]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470) ~[patched_1.17.1.jar:git-Airplane-73]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1275) ~[patched_1.17.1.jar:git-Airplane-73]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-73]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.world.InventorySubcontainer net.minecraft.world.entity.npc.EntityVillager.fD()'
        at de.Keyle.MyPet.compat.v1_17_R1.services.EntityConverterService.convertEntity(EntityConverterService.java:271) ~[MyPet-3.12-RC3.jar:?]
        at de.Keyle.MyPet.commands.CommandRelease.lambda$onCommand$0(CommandRelease.java:95) ~[MyPet-3.12-RC3.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at de.Keyle.MyPet.commands.CommandRelease.onCommand(CommandRelease.java:95) ~[MyPet-3.12-RC3.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Airplane-73]
        ... 21 more
```
[21:08:07 INFO]: This server is running Airplane version git-Airplane-73 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: a8f82ed on HEAD)
Unknown version
Previous version: git-Airplane-"ec7d3d0" (MC: 1.17.1)

**Comment by Jakllp** [comment]
Seems to be a problem when the villager has an inventory/other attributes

**Comment by Jakllp** [comment]
I think I found the issue?
'entityVillager.getInventory().addItem(itemstack);' looks right -> but it gets remapped to 'entityVillager.fD().a(itemstack) ' (seemingly).

This is wrong as it should be remapped to 'entityVillager.fG().a(itemstack)'

**Comment by Ghost-chu** [comment]
maybe need update mapping from 1.17 to 1.17.1












Ghost_chu
***@***.***


---Original---
From: ***@***.***&gt;
Date: Tue, Sep 7, 2021 00:21 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Jakllp/MyPet] Bug: Cannot release Villager? (#53)




 
I think I found the issue?
 'entityVillager.getInventory().addItem(itemstack);' looks right -&gt; but it gets remapped to 'entityVillager.fD().a(itemstack) ' (seemingly).
 
This is wrong as it should be remapped to 'entityVillager.fG().a(itemstack)'

**Comment by Jakllp** [comment]
Nope already using 1.17.1 (checked that immediately) - it's just wrong I guess.
Was technically able to get it over to bukkit api BUT I gotta reproduce the original error first

**Comment by Jakllp** [comment]
Done in https://github.com/Jakllp/MyPet/commit/b1d3da0ea975ea8270a95d13af1d11f41c56d0d9
