### ISSUE TITLE
Bug: Don’t know what caused this yet

### ISSUE THREAD

**Issue by Jakllp** [Jakllp/MyPet#56]
```
[15:05:23 ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1654) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:493) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1374]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.UnsupportedOperationException
        at de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPetPart.getPacket(EntityMyPetPart.java:78) ~[MyPet-3.12-RC3.jar:?]
        at net.minecraft.server.level.ServerEntity.a(ServerEntity.java:299) ~[app:?]
        at net.minecraft.server.level.ServerEntity.addPairing(ServerEntity.java:287) ~[app:?]
        at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayer(ChunkMap.java:2392) ~[app:?]
        at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayers(ChunkMap.java:2303) ~[app:?]
        at net.minecraft.server.level.ChunkMap.processTrackQueue(ChunkMap.java:2049) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:2070) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1083) ~[app:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:934) ~[app:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:756) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1635) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:493) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Purpur-1374]
        ... 2 more
[15:05:23 ERROR]:       Cause of unexpected exception was
java.lang.UnsupportedOperationException: null
        at de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPetPart.getPacket(EntityMyPetPart.java:78) ~[MyPet-3.12-RC3.jar:?]
        at net.minecraft.server.level.ServerEntity.a(ServerEntity.java:299) ~[app:?]
        at net.minecraft.server.level.ServerEntity.addPairing(ServerEntity.java:287) ~[app:?]
        at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayer(ChunkMap.java:2392) ~[app:?]
        at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayers(ChunkMap.java:2303) ~[app:?]
        at net.minecraft.server.level.ChunkTracker.processTrackQueue(ChunkTracker.java:2049) ~[app:?]
        at net.minecraft.server.level.ChunkTracker.tick(ChunkTracker.java:2070) ~[app:?]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1083) ~[app:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:934) ~[app:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:756) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1635) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:493) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Purpur-1374]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1374]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Jakllp** [comment]
Should be fixed in https://github.com/Jakllp/MyPet/commit/0844ddc938908a6fffd1c809f4bafb1360c1dbd4
See https://github.com/Jakllp/MyPet/releases/tag/3.12-RC4
