### ISSUE TITLE
Bug: No value present - Control-Skill

### ISSUE THREAD

**Issue by Jakllp** [Jakllp/MyPet#60]
```
[07:12:50] [Server thread/WARN]: java.util.NoSuchElementException: No value present
[07:12:50] [Server thread/WARN]: 	at java.base/java.util.Optional.get(Optional.java:143)
[07:12:50] [Server thread/WARN]: 	at MyPet-3.12-SNAPSHOT-B1646.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.ai.movement.Control.shouldStart(Control.java:55)
[07:12:50] [Server thread/WARN]: 	at MyPet-3.12-SNAPSHOT-B1646.jar//de.Keyle.MyPet.api.entity.ai.AIGoalSelector.tick(AIGoalSelector.java:124)
[07:12:50] [Server thread/WARN]: 	at MyPet-3.12-SNAPSHOT-B1646.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.doMyPetTick(EntityMyPet.java:1182)
[07:12:50] [Server thread/WARN]: 	at MyPet-3.12-SNAPSHOT-B1646.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.movementTick(EntityMyPet.java:1065)
[07:12:50] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityLiving.tick(EntityLiving.java:2895)
[07:12:50] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityInsentient.tick(EntityInsentient.java:393)
[07:12:50] [Server thread/WARN]: 	at MyPet-3.12-SNAPSHOT-B1646.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.tick(EntityMyPet.java:1381)
[07:12:50] [Server thread/WARN]: 	at net.minecraft.server.level.WorldServer.entityJoinedWorld(WorldServer.java:1129)
[07:12:50] [Server thread/WARN]: 	at net.minecraft.server.level.WorldServer.lambda$tick$7(WorldServer.java:777)
[07:12:50] [Server thread/WARN]: 	at net.minecraft.server.level.WorldServer$$Lambda$8900/0x0000000073726650.accept(Unknown Source)
[07:12:50] [Server thread/WARN]: 	at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:43)
[07:12:50] [Server thread/WARN]: 	at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:756)
[07:12:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1619)
[07:12:50] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:481)
[07:12:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475)
[07:12:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274)
[07:12:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[07:12:50] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer$$Lambda$3681/0x0000000041ecc1d0.run(Unknown Source)
[07:12:50] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:853)
```

**Comment by Jakllp** [comment]
Also happening on other versions

**Comment by Jakllp** [comment]
Control-Skill not working on 1.17.1 anyway

**Comment by Jakllp** [comment]
Potentially fixed in https://github.com/Jakllp/MyPet/commit/c7471ade32afcb1964734842565c85c58e17db76
