### ISSUE TITLE
Bug: No such Method - getOwner -> Tameable entities

### ISSUE THREAD

**Issue by Jakllp** [Jakllp/MyPet#61]
```
java.lang.NoSuchMethodError: 'net.minecraft.world.entity.EntityLiving net.minecraft.world.entity.EntityTameableAnimal.fw()'
	at de.Keyle.MyPet.compat.v1_17_R1.entity.ai.target.BehaviorAggressiveTarget.shouldStart(BehaviorAggressiveTarget.java:89)
	at de.Keyle.MyPet.api.entity.ai.AIGoalSelector.tick(AIGoalSelector.java:124)
	at de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.doMyPetTick(EntityMyPet.java:1181)
	at de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.movementTick(EntityMyPet.java:1065)
	at net.minecraft.world.entity.EntityLiving.tick(EntityLiving.java:2805)
	at net.minecraft.world.entity.EntityInsentient.tick(EntityInsentient.java:375)
	at de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.tick(EntityMyPet.java:1381)
	at net.minecraft.server.level.WorldServer.entityJoinedWorld(WorldServer.java:815)
	at net.minecraft.world.level.World.a(World.java:692)
	at net.minecraft.server.level.WorldServer.lambda$11(WorldServer.java:527)
	at net.minecraft.world.level.entity.EntityTickList.a(SourceFile:54)
	at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:508)
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1297)
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:436)
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200)
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1027)
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
	at java.base/java.lang.Thread.run(Thread.java:831)
```
	
This actually crashes servers - might be caused by a mojang-mapping error (fun - see getOwner )

**Comment by Jakllp** [comment]
Should be fixed in https://github.com/Jakllp/MyPet/commit/c180a19a253fe667c47902fdaa293ed000fac1a3
