### ISSUE TITLE
Bug: PacketError with certain entities

### ISSUE THREAD

**Issue by Jakllp** [Jakllp/MyPet#62]
```
[17:06:23] [Craft Scheduler Thread - 23/ERROR]: [MyPet] Unhandled exception occured in onPacketSending(PacketEvent) for MyPet
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[server.jar:3241-Spigot-6c1c1b2-1492826]
        at net.minecraft.server.level.WorldServer.getEntities(WorldServer.java:1757) ~[server.jar:3241-Spigot-6c1c1b2-1492826]
        at net.minecraft.server.level.WorldServer.getEntity(WorldServer.java:1268) ~[server.jar:3241-Spigot-6c1c1b2-1492826]
        at de.Keyle.MyPet.compat.v1_17_R1.PlatformHelper.getEntity(PlatformHelper.java:372) ~[MyPet-3.12-SNAPSHOT-B1646.jar:?]
        at de.Keyle.MyPet.util.hooks.ProtocolLibHook$2.onPacketSending(ProtocolLibHook.java:157) ~[MyPet-3.12-SNAPSHOT-B1646.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.7.0]
        at net.minecraft.network.NetworkManager.b(NetworkManager.java:203) [server.jar:3241-Spigot-6c1c1b2-1492826]
        at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:183) [server.jar:3241-Spigot-6c1c1b2-1492826]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1695) [server.jar:3241-Spigot-6c1c1b2-1492826]
        at net.minecraft.server.network.PlayerConnection.sendPacket(PlayerConnection.java:1681) [server.jar:3241-Spigot-6c1c1b2-1492826]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at ak.znetwork.znpcservers.utility.Utils.sendPackets(Utils.java:150) [znpc-servers.jar:?]
        at ak.znetwork.znpcservers.npc.NPC.lookAt(NPC.java:402) [znpc-servers.jar:?]
        at ak.znetwork.znpcservers.npc.NPC.spawn(NPC.java:333) [znpc-servers.jar:?]
        at ak.znetwork.znpcservers.tasks.NPCManagerTask.run(NPCManagerTask.java:40) [znpc-servers.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) [server.jar:3241-Spigot-6c1c1b2-1492826]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [server.jar:3241-Spigot-6c1c1b2-1492826]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```
Similar to other packet error - should be easy to fix

**Comment by Jakllp** [comment]
Should be fixed in https://github.com/Jakllp/MyPet/commit/c180a19a253fe667c47902fdaa293ed000fac1a3
