### ISSUE TITLE
InventoryClickError (BossShopPro is involved) - As reported by UmNyom

### ISSUE THREAD

**Issue by Jakllp** [Jakllp/MyPet#7]
# Bug report

Error as reported by @UmNyom in https://github.com/Jakllp/MyPet/issues/3

## To Reproduce

1. ? (something to do with BossShopPro?)

**Error:**
```
[16:24:32 ERROR]: Could not pass event InventoryClickEvent to BossShopPro v2.0.15
[16:24:32 ERROR]: Suspected Plugins:
[16:24:32 ERROR]:       MyPet{enabled,ver=3.12,path=plugins\MyPet-3.12-SNAPSHOT.jar}
[16:24:32 ERROR]:       BossShopPro{enabled,ver=2.0.15,path=plugins\BossShopPro.jar}
[16:24:32 ERROR]: Exception details below:
org.bukkit.command.CommandException: Unhandled exception executing command 'petshop' in plugin MyPet v3.12
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[ssspigot2187240887410612006.jar:SSSpigot2-1.17.1-20210817-85ace39]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[ssspigot2187240887410612006.jar:SSSpigot2-1.17.1-20210817-85ace39]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:832) ~[ssspigot2187240887410612006.jar:SSSpigot2-1.17.1-20210817-85ace39]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:647) ~[ssspigot2187240887410612006.jar:SSSpigot2-1.17.1-20210817-85ace39]
        at org.black_ixx.bossshop.core.rewards.BSRewardTypePlayerCommandOp.executeCommands(BSRewardTypePlayerCommandOp.java:65) ~[BossShopPro.jar:?]
        at org.black_ixx.bossshop.core.rewards.BSRewardTypePlayerCommandOp.giveReward(BSRewardTypePlayerCommandOp.java:44) ~[BossShopPro.jar:?]
        at org.black_ixx.bossshop.core.BSBuy.purchase(BSBuy.java:505) ~[BossShopPro.jar:?]
        at org.black_ixx.bossshop.core.BSBuy.purchaseTask(BSBuy.java:447) ~[BossShopPro.jar:?]
        at org.black_ixx.bossshop.core.BSBuy.purchaseTry(BSBuy.java:421) ~[BossShopPro.jar:?]
        at org.black_ixx.bossshop.core.BSBuy.click(BSBuy.java:390) ~[BossShopPro.jar:?]
        at org.black_ixx.bossshop.listeners.InventoryListener.purchase(InventoryListener.java:189) ~[BossShopPro.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor940.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[ssspigot2187240887410612006.jar:SSSpigot2-1.17.1-20210817-85ace39]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[ssspigot2187240887410612006.jar:SSSpigot2-1.17.1-20210817-85ace39]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[ssspigot2187240887410612006.jar:SSSpigot2-1.17.1-20210817-85ace39]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:633) ~[ssspigot2187240887410612006.jar:SSSpigot2-1.17.1-20210817-85ace39]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2810) ~[ssspigot2187240887410612006.jar:SSSpigot2-1.17.1-20210817-85ace39]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:55) ~[ssspigot2187240887410612006.jar:SSSpigot2-1.17.1-20210817-85ace39]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:11) ~[ssspigot2187240887410612006.jar:SSSpigot2-1.17.1-20210817-85ace39]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[ssspigot2187240887410612006.jar:SSSpigot2-1.17.1-20210817-85ace39]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:152) ~[ssspigot2187240887410612006.jar:SSSpigot2-1.17.1-20210817-85ace39]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:24) ~[ssspigot2187240887410612006.jar:SSSpigot2-1.17.1-20210817-85ace39]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:124) ~[ssspigot2187240887410612006.jar:SSSpigot2-1.17.1-20210817-85ace39]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1423) ~[ssspigot2187240887410612006.jar:SSSpigot2-1.17.1-20210817-85ace39]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1416) ~[ssspigot2187240887410612006.jar:SSSpigot2-1.17.1-20210817-85ace39]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:135) ~[ssspigot2187240887410612006.jar:SSSpigot2-1.17.1-20210817-85ace39]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1389) ~[ssspigot2187240887410612006.jar:SSSpigot2-1.17.1-20210817-85ace39]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1299) ~[ssspigot2187240887410612006.jar:SSSpigot2-1.17.1-20210817-85ace39]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[ssspigot2187240887410612006.jar:SSSpigot2-1.17.1-20210817-85ace39]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.server.level.EntityPlayer cannot be cast to class net.minecraft.world.inventory.ICrafting (net.minecraft.server.level.EntityPlayer and net.minecraft.world.inventory.ICrafting are in unnamed module of loader 'app')
        at de.Keyle.MyPet.compat.v1_17_R1.util.inventory.CustomInventory.open(CustomInventory.java:329) ~[MyPet-3.12-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.compat.v1_17_R1.util.iconmenu.IconMenuInventory.open(IconMenuInventory.java:84) ~[MyPet-3.12-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.api.gui.IconMenu.open(IconMenu.java:97) ~[MyPet-3.12-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.commands.CommandShop.onCommand(CommandShop.java:149) ~[MyPet-3.12-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[ssspigot2187240887410612006.jar:SSSpigot2-1.17.1-20210817-85ace39]
        ... 29 more
```

**Comment by Jakllp** [comment]
Might be solved? See https://github.com/Jakllp/MyPet/issues/8

**Comment by Jakllp** [comment]
Is solved! Was solved in https://github.com/Jakllp/MyPet/commit/e5ba2b73e130510615dbf5e08f177d2406e9f9c3

Wasn't obvious to me at first glance
