### ISSUE TITLE
[Bug] /pcst being blocked by IllegalStack (1.18-dev1)

### ISSUE THREAD

**Issue by comonier** [Jakllp/MyPet#75]
Bugs:

1 ➜ It says dont have permission to use command: petstore
but i give it
    - MyPet.shop.storage
    - MyPet.petstorage.limit.54
    
2 ➜ Other plugin blocking /pcst command
[19:05:18 INFO]: [IllegalStack/Log] Found a book with characters that do NOT match the specified character set and removed it.. Author was: UNKNOWN

**Comment by Jakllp** [comment]
To the first one:
MyPet.command.store is what you need (MyPet.shop.storage enables you to buy pets directly into storage)

The second one:
Interesting - This seems to be caused by one of the skilltrees (Farm) using a book as its icon and that plugin not liking that.
I might look into it but for now you can just edit the Farm-Skilltree to have a different icon

**Comment by Jakllp** [comment]
Also: On which Minecraft-Version was this? 1.18?

**Comment by comonier** [comment]
> Also: On which Minecraft-Version was this? 1.18?

Paper 1.18 

> To the first one: MyPet.command.store

Ty <3 i didnt know about that permission

**Comment by comonier** [comment]
- MyPet.command.store
    
    i just check i have it - so why it still saying to player cant use petstore command ?

**Comment by comonier** [comment]
- -MyPet.admin
    - MyPet.command.info.other
    - MyPet.command.capturehelper
    - MyPet.command.release
    - MyPet.command.respawn
    - MyPet.command.name
    - MyPet.command.name.color
    - MyPet.command.switch
    - MyPet.command.store
    - MyPet.command.trade.offer.*
    - MyPet.command.trade.receive.*
    - MyPet.shop.access.*
    - MyPet.shop.storage
    - MyPet.petstorage.limit.54
    - MyPet.leash.Bat
    - MyPet.leash.Bee
    - MyPet.leash.Blaze
    - MyPet.leash.Cat
    - MyPet.leash.CaveSpider
    - MyPet.leash.Chicken
    - MyPet.leash.Cod
    - MyPet.leash.Cow
    - MyPet.leash.Creeper
    - MyPet.leash.Dolphin
    - MyPet.leash.Donkey
    - MyPet.leash.Drowned
    - MyPet.leash.ElderGuardian
    - -MyPet.leash.EnderDragon
    - MyPet.leash.Enderman
    - MyPet.leash.Endermite
    - MyPet.leash.Evoker
    - MyPet.leash.Fox
    - MyPet.leash.Ghast
    - -MyPet.leash.Giant
    - MyPet.leash.Guardian
    - MyPet.leash.Hoglin
    - MyPet.leash.Horse
    - MyPet.leash.Husk
    - -MyPet.leash.Illusioner
    - -MyPet.leash.IronGolem
    - MyPet.leash.Llama
    - MyPet.leash.MagmaCube
    - MyPet.leash.Mooshroom
    - MyPet.leash.Mule
    - MyPet.leash.Ocelot
    - MyPet.leash.Panda
    - MyPet.leash.Parrot
    - MyPet.leash.Phantom
    - MyPet.leash.Pig
    - MyPet.leash.Piglin
    - MyPet.leash.PiglinBrute
    - MyPet.leash.PigZombie
    - MyPet.leash.Pillager
    - MyPet.leash.PolarBear
    - MyPet.leash.Pufferfish
    - MyPet.leash.Rabbit
    - MyPet.leash.Ravage
    - MyPet.leash.Salmon
    - MyPet.leash.Sheep
    - MyPet.leash.Silverfish
    - MyPet.leash.Skeleton
    - MyPet.leash.SkeletonHorse
    - MyPet.leash.Slime
    - MyPet.leash.Snowman
    - MyPet.leash.Spider
    - MyPet.leash.Squid
    - MyPet.leash.Stray
    - MyPet.leash.Strider
    - -MyPet.leash.TraderLlama
    - MyPet.leash.TropicalFish
    - MyPet.leash.Turtle
    - MyPet.leash.Vex
    - MyPet.leash.Villager
    - MyPet.leash.Vindicator
    - -MyPet.leash.WanderingTrader
    - MyPet.leash.Witch
    - -MyPet.leash.Wither
    - MyPet.leash.WitherSkeleton
    - MyPet.leash.Wolf
    - MyPet.leash.Zoglin
    - MyPet.leash.Zombie
    - MyPet.leash.ZombifiedPiglin
    - MyPet.leash.ZombieHorse
    - MyPet.leash.ZombieVillager
    - MyPet.skilltree.*
    - MyPet.skilltree.Combat
    - MyPet.skilltree.Utility
    - MyPet.skilltree.PvP
    - MyPet.skilltree.Ride
    - MyPet.skilltree.Farm
    - -MyPet.experience.multiplier.250
    - -MyPet.experience.multiplier.225
    - -MyPet.experience.multiplier.200
    - -MyPet.experience.multiplier.175
    - -MyPet.experience.multiplier.150
    - -MyPet.experience.multiplier.125
    - -MyPet.npc.storage
    - -MyPet.npc.shop
    - MyPet.extended.feed
    - MyPet.extended.beacon
    - MyPet.extended.behavior.friendly
    - MyPet.extended.behavior.aggressive
    - MyPet.extended.behavior.farm
    - MyPet.extended.behavior.raid
    - MyPet.extended.behavior.duel
    - MyPet.extended.inventory
    - MyPet.extended.ride
    - -MyPet.extended.ride.fly
    - MyPet.extended.control
    - MyPet.extended.pickup
    - MyPet.extended.equip
    - MyPet.extended.nametag
    - MyPet.Skill.Ride.Item

**Comment by comonier** [comment]
after update  `MyPet-3.12-SNAPSHOT-B1655.jar (1655  14 hours ago)`
`[19:42:32 INFO]: reinomoc issued server command: /petc
[19:42:32 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'petc' in plugin MyPet v3.12 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:878) ~[paper-1.18.jar:git-Paper-22]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2201) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2012) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1993) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.jar:git-Paper-22]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1412) ~[paper-1.18.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.jar:git-Paper-22]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1390) ~[paper-1.18.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1383) ~[paper-1.18.jar:git-Paper-22]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1517) ~[paper-1.18.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1263) ~[paper-1.18.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.jar:git-Paper-22]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
>`

**Comment by Jakllp** [comment]
Yeah the jars over on the download-page aren't compatible with 1.18 yet (only 3.12-1.18-dev1 is)

To the permission thing: Can you tell me exactly what it says when you execute the command?
I just tested it and it works for me so I'm curious

**Comment by comonier** [comment]
Going back to **MyPet-3.12-1.18-dev1.jar**
```java
[19:53:59] [Server thread/INFO]: [MyPet] Loading MyPet v3.12
[19:53:59] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [mError-Reporter ENABLED[m
[19:54:15] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [mEnabling MyPet v3.12[m
[19:54:15] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [mNo Update available.[m
[19:54:15] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [mCompat mode for v1_18_R1 loaded.[m
[19:54:15] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [mExp calculation mode: MyPet[m
[19:54:15] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [mLoading WorldGroups...[m
[19:54:15] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [m   added '[0;33;22mworld[m' to 'default'[m
[19:54:15] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [m   added '[0;33;22mworld_nether[m' to 'default'[m
[19:54:15] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [m   added '[0;33;22mworld_the_end[m' to 'default'[m
[19:54:15] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [mConnect to SQLite database...[m
[19:54:15] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [mSQLite connection successful.[m
[19:54:15] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [mGriefPrevention (16.17.1-2b69191) hook activated.[m
[19:54:15] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [mmcMMO (2.1.198) hook activated.[m
[19:54:15] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: mypet
[19:54:15] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [mPlaceholderAPI (2.10.10) hook activated.[m
[19:54:15] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [mProtocolLib (4.7.0-SNAPSHOT-b526) hook activated.[m
[19:54:15] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [mSimpleClans (2.15.3) hook activated.[m
[19:54:15] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [mVault (1.7.3-b131) (Economy: Essentials Economy) (Permissions: PermissionsEx) hook activated.[m
[19:54:15] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [mWorldGuard (7.0.6-SNAPSHOT+2121-32d16a7) hook activated.[m
[19:54:15] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [mVersion 3.12-1.18-dev1-b[0;32;1m ENABLED[m
```
config.yml
```
# #################################################################
#            This is the main configuration of MyPet              #
#              You can find more info on the wiki:                #
#   https://wiki.mypet-plugin.de/setup/configurations/config.yml  #
# #################################################################

MyPet:
  Update:
    Check: true
    Download: false
    ReplaceOld: false
    In-Background: false
    OP-Notification: true
  Leash:
    Consume: false
    AllowRanged: true
  OwnerCanAttackPet: false
  DisablePetVersusPlayer: false
  RetainEquipmentOnTame: true
  Make-Pet-Invisible-When-Owner-Is-Invisible: true
  Log:
    Level: INFO
    Report-Errors: true
    Unique-ID: de57a589-9d96-4727-8e9b-8d0fb8039fb3
  Max-Stored-Pet-Count: 45
  Throw-PlayerMoveEvent-While-Riding: true
  Disable-All-Actionbar-Messages: false
  OverwriteLanguages: ''
  Right-Click-Command: ''
  Entity:
    Skip-Target-AI-Ticks: 0
    FollowStartDistance: 7.0
  Repository:
    Type: SQLite
    ConvertFrom: ''
    LoadDelay: 20
    MySQL:
      Database: mypet
      TablePrefix: ''
      Host: localhost
      Password: ''
      User: root
      Port: 3306
      MaxConnections: 12
      CharacterEncoding: utf8
    MongoDB:
      Database: mypet
      CollectionPrefix: ''
      Host: localhost
      Password: ''
      User: ''
      Port: 27017
  Respawn:
    Time:
      Disabled: false
      Default:
        Factor: 5
        Fixed: 0
      Player:
        Factor: 5
        Fixed: 0
    EconomyCost:
      Fixed: 0.0
      Factor: 1.0
  Permissions:
    Enabled: true
    Extended: false
    Legacy: false
  LevelSystem:
    CalculationMode: Default
  HungerSystem:
    Active: true
    Time: 60
    SaturationPerFeed: 6.0
    Affect-Ride-Speed: true
    Affect-Beacon-Range: true
  Skilltree:
    AutomaticAssignment: false
    RandomAssignment: false
    ChooseOnce: false
    PreventLevellingWithout: true
    SwitchFee:
      Fixed: 0.0
      Percent: 5
      Admin: false
  Name:
    Filter:
    - whore
    - fuck
    MaxLength: 32
    Tag:
      Show: true
      Prefix: <aqua>
      Suffix: ''
  Exp:
    DamageWeightedExperienceDistribution: true
    Passive:
      Always-Grant-Passive-XP: true
      PercentPerMonster: 25
    Loss:
      Percent: 0
      Fixed: 0.0
      Drop: true
      Allow-Level-Drowngrade: false
    Gain:
      PreventFromSpawnReason: []
    LevelCap: 100
    Disabled-Worlds: []
    Modifier:
      Global: 1.0
      Use-Permissions: false
  Skill:
    Control:
      Item: lead
    Backpack:
      Creative: false
      DropWhenOwnerDies: false
    Beacon:
      HungerDecreaseTime: 100
      Disable-Head-Textures: false
      Party-Support: true
    Ride:
      Item: lead
      HungerPerMeter: 0.01
      Prevent-Teleportation-While-Riding: false
  Info:
    Wiki-URL: https://wiki.mypet-plugin.de

```

**Comment by comonier** [comment]
when i trie use command /petstore it give me the answer [in portuguese]
Você não tem permissão para usar isso! (You are not allowed to use this) with not in red color.

**Comment by comonier** [comment]
![image](https://user-images.githubusercontent.com/19571541/144517070-fcadc577-6b29-41c7-ab4a-f59a53a5d8cf.png)

**Comment by comonier** [comment]
```java
[20:06:25 INFO]: reinomoc issued server command: /pcst
[20:06:25 INFO]: [IllegalStack/Log] Found a book with characters that do NOT match the specified character set and removed it.. Author was: UNKNOWN
```
/pcst still being blocked by dupe fixe illegal stacks

**Comment by comonier** [comment]
```java
[20:08:41 INFO]: This server is running Paper version git-Paper-22 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 956124f)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads
```

**Comment by Jakllp** [comment]
To the pcst thing: Again - Just change the icon of the farm skilltree to something else than a book. That's the easiest way for now before I get around fixing that plugin compatibility issue

**Comment by Jakllp** [comment]
Do other commands like /petname work?

**Comment by comonier** [comment]
all other works, if i try buy something from store it says i cant have more than 0 pets i gues its something wrong on permissions there is a max of pets a players can have ? cause i guess i put 54

**Comment by comonier** [comment]
> To the pcst thing: Again - Just change the icon of the farm skilltree to something else than a book. That's the easiest way for now before I get around fixing that plugin compatibility issue

on each file i change that book item ?

**Comment by comonier** [comment]
> > To the pcst thing: Again - Just change the icon of the farm skilltree to something else than a book. That's the easiest way for now before I get around fixing that plugin compatibility issue
> 
> on each file i change that book item ?

i guess i found it
```java
  "MobTypes": [
    "*"
  ],
  "ID": "Farm",
  "Icon": {
    "Material": "writable_book"
  },
  "Name": "Farm"
}
```

**Comment by comonier** [comment]
![image](https://user-images.githubusercontent.com/19571541/144519204-5a365cf2-363c-45c8-a02a-d04fb0829537.png)
everything solved thanks, the pcst problem solved by changing the item to wheat and the petstore problem solved when I changed the limit of pets that the player can have from 54 to 45

ty <3

**Comment by Jakllp** [comment]
Nice!
Have fun with your pets ^^
