### ISSUE TITLE
Bug: Donkey-Spawning throws StackOverflow

### ISSUE THREAD

**Issue by UmNyom** [Jakllp/MyPet#8]
```
[15:54:22 INFO]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] de.Keyle.MyPet.compat.v1_17_R1.entity.types.EntityMyDonkey(Donkey) is no valid MyPet(Entity)!
[15:54:22 WARN]: java.lang.reflect.InvocationTargetException
[15:54:22 WARN]:        at jdk.internal.reflect.GeneratedConstructorAccessor186.newInstance(Unknown Source)
[15:54:22 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:54:22 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[15:54:22 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[15:54:22 WARN]:        at MyPet-3.12-DEV2.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityRegistry.createMinecraftEntity(EntityRegistry.java:93)
[15:54:22 WARN]:        at MyPet-3.12-DEV2.jar//de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:473)
[15:54:22 WARN]:        at MyPet-3.12-DEV2.jar//de.Keyle.MyPet.util.player.MyPetPlayerImpl.schedule(MyPetPlayerImpl.java:481)
[15:54:22 WARN]:        at MyPet-3.12-DEV2.jar//de.Keyle.MyPet.api.util.Timer.lambda$startTimer$2(Timer.java:62)
[15:54:22 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:54:22 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[15:54:22 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1609)
[15:54:22 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:502)
[15:54:22 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1515)
[15:54:22 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1289)
[15:54:22 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[15:54:22 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[15:54:22 WARN]: Caused by: java.lang.StackOverflowError
[15:54:22 WARN]:        at java.base/java.util.HashMap.hash(HashMap.java:340)
[15:54:22 WARN]:        at java.base/java.util.HashMap.getNode(HashMap.java:570)
[15:54:22 WARN]:        at java.base/java.util.HashMap.containsKey(HashMap.java:596)
[15:54:22 WARN]:        at MyPet-3.12-DEV2.jar//de.Keyle.MyPet.api.entity.MyPetInfo.getStartHP(MyPetInfo.java:100)
[15:54:22 WARN]:        at MyPet-3.12-DEV2.jar//de.Keyle.MyPet.entity.MyPet.getMaxHealth(MyPet.java:201)
[15:54:22 WARN]:        at MyPet-3.12-DEV2.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.getHealth(EntityMyPet.java:694)
[15:54:22 WARN]:        at MyPet-3.12-DEV2.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.setHealth(EntityMyPet.java:704)
[15:54:22 WARN]:        at MyPet-3.12-DEV2.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.getHealth(EntityMyPet.java:696)
[15:54:22 WARN]:        at MyPet-3.12-DEV2.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.setHealth(EntityMyPet.java:704)
[15:54:22 WARN]:        at MyPet-3.12-DEV2.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.getHealth(EntityMyPet.java:696)
[15:54:22 WARN]:        at MyPet-3.12-DEV2.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.setHealth(EntityMyPet.java:704)
[15:54:22 WARN]:        at MyPet-3.12-DEV2.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.getHealth(EntityMyPet.java:696)
[15:54:22 WARN]:        at MyPet-3.12-DEV2.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.setHealth(EntityMyPet.java:704)
[15:54:22 WARN]:        at MyPet-3.12-DEV2.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.getHealth(EntityMyPet.java:696)
[15:54:22 WARN]:        at MyPet-3.12-DEV2.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.setHealth(EntityMyPet.java:704)
[15:54:22 WARN]:        at MyPet-3.12-DEV2.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.getHealth(EntityMyPet.java:696)
[15:54:22 WARN]:        at MyPet-3.12-DEV2.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.setHealth(EntityMyPet.java:704)
[15:54:22 WARN]:        at MyPet-3.12-DEV2.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.getHealth(EntityMyPet.java:696)
[15:54:22 WARN]:        at MyPet-3.12-DEV2.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.setHealth(EntityMyPet.java:704)
[15:54:22 WARN]:        at MyPet-3.12-DEV2.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.getHealth(EntityMyPet.java:696)
[15:54:22 WARN]:        at MyPet-3.12-DEV2.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.setHealth(EntityMyPet.java:704)
```
The error continues until Stack-Overflow

--- 
Hello, developer. Thank you for solving my issue last time. But there's another problem. . . .

Pets are not displayed in the inventory, and summoning pets causes problems.

I can't see my pet, and there's an error that I wasn't summoned by something.

**Comment by Jakllp** [comment]
Seems to be a donkey-specific error.

Thank you for reporting it

**Comment by Jakllp** [comment]
Probably a type-error

**Comment by Jakllp** [comment]
Fixed in https://github.com/Jakllp/MyPet/commit/89e9705a27a1154f27306f9da4a82179e4863047
