### ISSUE TITLE
Bug: Entity-Specific problems (Thanks edyangel)

### ISSUE THREAD

**Issue by Jakllp** [Jakllp/MyPet#9]
The following Pets don't function as expected:

- [x] Error in console (Health error just as #8):
Enderman
Elder Guardian
Guardian
evoker
pillager
turtle
vindicator
Witch

- [x] Appears and disappears instantly:
Rabbit 
Gotta love Spigot and Paper: For Paper this is getPath() in Spigot it is k() - Wow. Don't know how to go about this yet
Fixed the error by removing the check - will probably result in rabbits just jumping around all the time. We'll see. Later.
```
java.lang.NoSuchMethodError: 'net.minecraft.world.level.pathfinder.PathEntity net.minecraft.world.entity.ai.navigation.NavigationAbstract.k()'
	at de.Keyle.MyPet.compat.v1_17_R1.entity.types.EntityMyRabbit.onLivingUpdate(EntityMyRabbit.java:108) ~[?:?]
	at de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.tick(EntityMyPet.java:1396) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:903) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:869) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:600) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54) ~[patched_1.17.1.jar:git-Paper-145]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:581) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1553) ~[patched_1.17.1.jar:git-Paper-145]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-145]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-145]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-145]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-145]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

- [ ] Cannot be attacked:
villager
zombie villager
Wither skeleton

- [x] Die ("die without being tamed"?):
cats
donkey (potentially see #8)
ghast
glow squid
horse
llama
trade llama
mule
parrot2
Piglin Brute
polar bear
pufferfish
Ravager
Shulker
stray
Wandering Trader

**Comment by Jakllp** [comment]
@edyangel What exactly do you mean by "cannot be attacked" - Other players attacking the Pet?

**Comment by Jakllp** [comment]
Most if not all should be fixed in https://github.com/Jakllp/MyPet/commit/89e9705a27a1154f27306f9da4a82179e4863047

Waiting for feedback from @edyangel

**Comment by Jakllp** [comment]
Should basically be done - not completely sure tho
